"""Focused tests for dependency version-policy helpers and generated values."""

import re
import urllib.error
from collections import OrderedDict
from collections.abc import Callable
from email.message import Message
from io import BytesIO
from pathlib import Path

import pytest

from scripts import update_dependencies

_ROOT = Path(__file__).parent.parent
_MOVED_NPM_FEATURES = (
    "ghcr.io/devcontainers-extra/features/claude-code:2",
    "ghcr.io/devcontainers-extra/features/opencode:1",
    "ghcr.io/devcontainers/features/copilot-cli:1",
)


@pytest.mark.parametrize(
    ("version", "expected"),
    [
        ("0.144.1", "0.x"),
        ("7.4.5", "7.x"),
        ("11.10.0", "11.x"),
        ("12.0.0-beta.1", "12.x"),
        ("12.0.0+build.2", "12.x"),
    ],
)
def test_npm_major_range_allows_minor_and_patch_releases(version, expected):
    assert update_dependencies.npm_major_range(version) == expected


def test_npm_major_range_rejects_non_concrete_versions():
    with pytest.raises(SystemExit, match="not a valid npm version"):
        update_dependencies.npm_major_range("0.x")


def test_generated_npm_ranges_match_their_devcontainer_consumers():
    values = update_dependencies.read_env(_ROOT / ".devcontainer" / "tool-versions.env")

    assert (
        frozenset(update_dependencies.NPM_VERSION_PINS)
        == update_dependencies.NPM_MAJOR_RANGE_KEYS
    )

    assert {key: values[key] for key in update_dependencies.NPM_MAJOR_RANGE_KEYS} == {
        "CLAUDE_CODE_VERSION": "2.x",
        "CODEX_VERSION": "0.x",
        "COPILOT_CLI_VERSION": "1.x",
        "KILO_VERSION": "7.x",
        "KIMI_CODE_VERSION": "0.x",
        "OPENCODE_VERSION": "1.x",
        "PNPM_VERSION": "11.x",
    }

    devcontainer = (_ROOT / ".devcontainer" / "devcontainer.json").read_text()
    assert '"pnpmVersion": "11.x"' in devcontainer

    lock = (_ROOT / ".devcontainer" / "devcontainer-lock.json").read_text()
    for feature in _MOVED_NPM_FEATURES:
        assert feature not in update_dependencies.FEATURE_OPTION_REFS
        assert feature not in devcontainer
        assert feature not in lock

    post_create = (_ROOT / ".devcontainer" / "postCreate.sh").read_text()
    assert '"@anthropic-ai/claude-code@$CLAUDE_CODE_VERSION"' in post_create
    assert '"@openai/codex@$CODEX_VERSION"' in post_create
    assert '"@github/copilot@$COPILOT_CLI_VERSION"' in post_create
    assert '"@kilocode/cli@$KILO_VERSION"' in post_create
    assert '"opencode-ai@$OPENCODE_VERSION"' in post_create
    assert '"@moonshot-ai/kimi-code@$KIMI_CODE_VERSION"' in post_create


def test_refresh_tool_versions_ranges_every_npm_package(monkeypatch):
    npm_versions = {
        "@anthropic-ai/claude-code": "2.1.205",
        "@openai/codex": "0.200.3",
        "@github/copilot": "1.2.3",
        "@kilocode/cli": "7.9.1",
        "@moonshot-ai/kimi-code": "0.29.1",
        "opencode-ai": "1.18.0",
        "pnpm": "11.12.0",
    }
    monkeypatch.setattr(
        update_dependencies, "latest_npm_version", npm_versions.__getitem__
    )
    monkeypatch.setattr(update_dependencies, "GITHUB_RELEASE_PINS", OrderedDict())
    monkeypatch.setattr(update_dependencies, "GITHUB_BINARY_PINS", OrderedDict())

    def _latest_node_version(_major: int) -> str:
        return "22.23.1"

    monkeypatch.setattr(
        update_dependencies, "latest_node_version", _latest_node_version
    )
    monkeypatch.setattr(
        update_dependencies, "latest_docker_cli_version", lambda: "29.6.1"
    )
    monkeypatch.setattr(update_dependencies, "latest_uv_version", lambda: "0.11.28")

    values = update_dependencies.refresh_tool_versions(
        OrderedDict([("NODE_VERSION", "22.23.1")])
    )

    assert values["CLAUDE_CODE_VERSION"] == "2.x"
    assert values["CODEX_VERSION"] == "0.x"
    assert values["COPILOT_CLI_VERSION"] == "1.x"
    assert values["KILO_VERSION"] == "7.x"
    assert values["KIMI_CODE_VERSION"] == "0.x"
    assert values["OPENCODE_VERSION"] == "1.x"
    assert values["PNPM_VERSION"] == "11.x"


def test_uv_required_version_matches_generated_pin():
    values = update_dependencies.read_env(_ROOT / ".devcontainer" / "tool-versions.env")
    uv_config = (_ROOT / "uv.toml").read_text()

    assert f'required-version = "=={values["UV_VERSION"]}"' in uv_config


def test_write_uv_required_version(tmp_path):
    uv_config = tmp_path / "uv.toml"

    update_dependencies.write_uv_required_version(uv_config, "0.11.28")

    assert uv_config.read_text() == (
        "# Generated by scripts/update_dependencies.py.\n"
        'required-version = "==0.11.28"\n'
    )


def test_update_running_uv_bootstraps_new_version_before_config_changes(monkeypatch):
    calls: list[list[str]] = []
    monkeypatch.setattr(update_dependencies, "run", calls.append)

    update_dependencies.update_running_uv("0.11.28", "0.11.32")

    assert calls == [["uv", "self", "update", "0.11.32"]]


def test_update_running_uv_is_noop_when_version_is_current(monkeypatch):
    def _unexpected_run(_args: list[str]) -> None:
        pytest.fail("uv self-update must not run")

    monkeypatch.setattr(update_dependencies, "run", _unexpected_run)

    update_dependencies.update_running_uv("0.11.32", "0.11.32")


def test_refresh_devcontainer_bootstraps_uv_before_rewriting_config(
    tmp_path, monkeypatch
):
    tool_versions = tmp_path / "tool-versions.env"
    tool_versions.write_text("UV_VERSION=0.11.28\n")
    uv_config = tmp_path / "uv.toml"
    update_dependencies.write_uv_required_version(uv_config, "0.11.28")

    monkeypatch.setattr(update_dependencies, "TOOL_VERSIONS_FILE", tool_versions)
    monkeypatch.setattr(update_dependencies, "UV_TOML", uv_config)

    def _refresh_tool_versions(
        _existing: OrderedDict[str, str],
    ) -> OrderedDict[str, str]:
        return OrderedDict([("UV_VERSION", "0.11.32")])

    monkeypatch.setattr(
        update_dependencies,
        "refresh_tool_versions",
        _refresh_tool_versions,
    )

    def _ignore_values(_values: OrderedDict[str, str]) -> None:
        return None

    monkeypatch.setattr(
        update_dependencies,
        "update_devcontainer_json",
        _ignore_values,
    )
    monkeypatch.setattr(update_dependencies, "refresh_feature_lock", lambda: None)

    calls: list[list[str]] = []

    def _run(args: list[str]) -> None:
        assert 'required-version = "==0.11.28"' in uv_config.read_text()
        calls.append(args)

    monkeypatch.setattr(update_dependencies, "run", _run)

    update_dependencies.refresh_devcontainer_dependencies()

    assert calls == [["uv", "self", "update", "0.11.32"]]
    assert 'required-version = "==0.11.32"' in uv_config.read_text()
    assert update_dependencies.read_env(tool_versions)["UV_VERSION"] == "0.11.32"


def test_open_url_retries_transient_transport_failure(monkeypatch):
    attempts = 0
    sleeps: list[int] = []

    def _urlopen(_request, *, timeout):
        nonlocal attempts
        attempts += 1
        assert timeout == 30
        if attempts == 1:
            raise urllib.error.URLError(ConnectionResetError("reset"))
        return BytesIO(b'{"ok": true}')

    monkeypatch.setattr(update_dependencies.urllib.request, "urlopen", _urlopen)
    monkeypatch.setattr(update_dependencies.time, "sleep", sleeps.append)

    request = update_dependencies.urllib.request.Request("https://example.test/data")
    with update_dependencies.open_url(request, timeout=30) as response:
        assert response.read() == b'{"ok": true}'

    assert attempts == 2
    assert sleeps == [1]


def test_open_url_does_not_retry_permanent_http_error(monkeypatch):
    attempts = 0

    def _urlopen(request, *, timeout):
        nonlocal attempts
        attempts += 1
        headers: Message[str, str] = Message()
        raise urllib.error.HTTPError(request.full_url, 404, "not found", headers, None)

    monkeypatch.setattr(update_dependencies.urllib.request, "urlopen", _urlopen)

    def _unexpected_sleep(_delay: float) -> None:
        pytest.fail("permanent errors must not be retried")

    monkeypatch.setattr(
        update_dependencies.time,
        "sleep",
        _unexpected_sleep,
    )

    request = update_dependencies.urllib.request.Request("https://example.test/missing")
    with pytest.raises(urllib.error.HTTPError) as error:
        update_dependencies.open_url(request, timeout=30)

    assert error.value.code == 404
    assert attempts == 1


def test_update_tests_workflow_min_python_patches_both_matrix_entries(
    tmp_path, monkeypatch
):
    tests_workflow = tmp_path / "tests.yaml"
    tests_workflow.write_text(
        "  pytest:\n"
        "    strategy:\n"
        "      matrix:\n"
        "        include:\n"
        "          - ha-version: min\n"
        "            lockfile: requirements_test_min.lock.txt\n"
        '            python-version: "3.13"\n'
        "  e2e:\n"
        "    strategy:\n"
        "      matrix:\n"
        "        include:\n"
        "          - ha-version: min\n"
        "            lockfile: requirements_test_min.lock.txt\n"
        '            python-version: "3.13"\n'
    )
    monkeypatch.setattr(update_dependencies, "TESTS_WORKFLOW", tests_workflow)

    update_dependencies.update_tests_workflow_min_python("3.14")

    assert tests_workflow.read_text().count('python-version: "3.14"') == 2
    assert 'python-version: "3.13"' not in tests_workflow.read_text()


def test_update_tests_workflow_min_python_requires_exactly_two_matches(
    tmp_path, monkeypatch
):
    tests_workflow = tmp_path / "tests.yaml"
    tests_workflow.write_text(
        "  pytest:\n"
        "    strategy:\n"
        "      matrix:\n"
        "        include:\n"
        "          - ha-version: min\n"
        "            lockfile: requirements_test_min.lock.txt\n"
        '            python-version: "3.13"\n'
    )
    monkeypatch.setattr(update_dependencies, "TESTS_WORKFLOW", tests_workflow)

    with pytest.raises(SystemExit, match="expected exactly 2"):
        update_dependencies.update_tests_workflow_min_python("3.14")


def test_tests_workflow_min_python_version_is_identical_across_both_matrices():
    """Regression guard for the bug where only pytest's "ha-version: min"
    matrix entry was ever regenerated (count=1 on a pattern matching both
    it and e2e's identical block) -- meta-lint's actionlint has no way to
    catch this kind of semantic drift, since both spellings are valid YAML
    on their own.
    """
    text = (_ROOT / ".github" / "workflows" / "tests.yaml").read_text()
    matches = re.findall(
        r"- ha-version: min\n\s*lockfile: requirements_test_min\.lock\.txt\n"
        r'\s*python-version: "([^"]+)"',
        text,
    )
    assert len(matches) == 2, (
        "expected exactly 2 'ha-version: min' matrix entries in tests.yaml "
        f"(pytest's and e2e's), found {len(matches)}"
    )
    assert matches[0] == matches[1], (
        "pytest's and e2e's ha-version: min python-version have drifted "
        f"apart: {matches[0]!r} vs {matches[1]!r} -- see "
        "update_tests_workflow_min_python in scripts/update_dependencies.py"
    )


def test_exact_pins_extracts_only_unconditional_exact_pins(monkeypatch):
    requires_dist = [
        "aiohttp==3.14.1",
        "pyjwt[crypto]==2.12.1",
        # Range, not exact -- not something we can never independently bump.
        "awesomeversion>=25.8.0",
        # Marker-gated -- conditional, so not a pin our Linux-only CI
        # resolution is actually bound by.
        'pywin32==308; sys_platform == "win32"',
    ]

    def _fetch_json(_url: str) -> dict[str, object]:
        return {"info": {"requires_dist": requires_dist}}

    monkeypatch.setattr(update_dependencies, "fetch_json", _fetch_json)

    pins = update_dependencies.exact_pins("homeassistant", "2026.7.2")

    assert pins == {"aiohttp": "3.14.1", "pyjwt": "2.12.1"}


@pytest.mark.parametrize(
    ("name", "expected"),
    [
        ("PyJWT", "pyjwt"),
        ("pyjwt", "pyjwt"),
        ("aiohttp_cors", "aiohttp-cors"),
        ("atomicwrites.homeassistant", "atomicwrites-homeassistant"),
    ],
)
def test_normalize_pypi_name_collapses_pep503_equivalent_spellings(name, expected):
    assert update_dependencies.normalize_pypi_name(name) == expected


def test_locked_pin_reads_the_exact_version_from_a_pip_compile_style_line(tmp_path):
    lock_file = tmp_path / "requirements.lock.txt"
    lock_file.write_text(
        "attrs==26.1.0 \\\n"
        "    --hash=sha256:deadbeef\n"
        "homeassistant==2026.7.2 \\\n"
        "    --hash=sha256:deadbeef\n"
    )

    assert update_dependencies.locked_pin(lock_file, "homeassistant") == "2026.7.2"


def test_locked_pin_raises_when_the_package_is_not_pinned(tmp_path):
    lock_file = tmp_path / "requirements.lock.txt"
    lock_file.write_text("attrs==26.1.0 \\\n")

    with pytest.raises(SystemExit, match="could not find a homeassistant== pin"):
        update_dependencies.locked_pin(lock_file, "homeassistant")


def test_collect_dependabot_ignore_names_unions_and_normalizes_both_ha_legs(
    monkeypatch,
):
    monkeypatch.setattr(update_dependencies, "REQUIREMENTS_DEV_LOCK", "dev-lock")
    monkeypatch.setattr(update_dependencies, "REQUIREMENTS_TEST_MIN_LOCK", "min-lock")

    pinned_versions = {
        ("dev-lock", "homeassistant"): "2026.7.2",
        ("dev-lock", "pytest-homeassistant-custom-component"): "0.13.346",
        ("min-lock", "homeassistant"): "2026.1.0",
        ("min-lock", "pytest-homeassistant-custom-component"): "0.13.305",
    }

    def _locked_pin(lock_file: Path, name: str) -> str:
        return pinned_versions[(str(lock_file), name)]

    monkeypatch.setattr(update_dependencies, "locked_pin", _locked_pin)

    exact_pin_results = {
        ("homeassistant", "2026.7.2"): {
            "PyJWT": "2.12.1",
            "aiohttp": "3.14.1",
            "paho-mqtt": "2.1.0",
        },
        ("homeassistant", "2026.1.0"): {"pyjwt": "2.10.1"},
        ("pytest-homeassistant-custom-component", "0.13.346"): {
            "homeassistant": "2026.7.1",
            "pytest": "9.0.3",
        },
        ("pytest-homeassistant-custom-component", "0.13.305"): {"pytest": "9.0.0"},
    }

    def _exact_pins(package: str, version: str) -> dict[str, str]:
        return exact_pin_results[(package, version)]

    monkeypatch.setattr(update_dependencies, "exact_pins", _exact_pins)

    names = update_dependencies.collect_dependabot_ignore_names()

    # "PyJWT" and "pyjwt" from the two legs collapse into one normalized
    # entry; the two pytest pins from either phacc leg collapse likewise.
    assert names == ["aiohttp", "paho-mqtt", "pyjwt", "pytest"]


def test_update_dependabot_ignore_list_rewrites_generated_global_ignores(
    tmp_path, monkeypatch
):
    dependabot_yml = tmp_path / "dependabot.yml"
    dependabot_yml.write_text(
        "    ignore:\n"
        '      - dependency-name: "manual-root"\n'
        "      # <dependabot-ignore-generated>\n"
        '      - dependency-name: "stale"\n'
        "      # </dependabot-ignore-generated>\n"
    )
    monkeypatch.setattr(update_dependencies, "DEPENDABOT_YML", dependabot_yml)
    monkeypatch.setattr(
        update_dependencies,
        "collect_dependabot_ignore_names",
        lambda: ["aiohttp", "pyjwt"],
    )

    update_dependencies.update_dependabot_ignore_list()

    text = dependabot_yml.read_text()
    assert '      - dependency-name: "aiohttp"\n' in text
    assert '      - dependency-name: "pyjwt"\n' in text
    assert "manual-root" in text
    assert "exclude-patterns" not in text
    assert "stale" not in text


def test_real_dependabot_config_suppresses_exact_pin_prs_at_source() -> None:
    text = (_ROOT / ".github" / "dependabot.yml").read_text()
    ignore_block = text.split("    ignore:", 1)[1].split("    groups:", 1)[0]

    assert ignore_block.count("# <dependabot-ignore-generated>") == 1
    assert ignore_block.count("# </dependabot-ignore-generated>") == 1
    assert '      - dependency-name: "pytest"' in ignore_block
    assert "exclude-patterns:" not in text


def test_minimum_requirements_are_test_only() -> None:
    requirements = {
        line.split("==", 1)[0].split(">=", 1)[0]
        for raw in (_ROOT / "requirements_test_min.txt").read_text().splitlines()
        if (line := raw.strip()) and not line.startswith("#")
    }

    assert {
        "pyserial",
        "pytest-homeassistant-custom-component",
        "pytest-cov",
    } <= requirements
    assert {
        "ruff",
        "pyright",
        "mypy",
        "pre-commit",
        "types-pyserial",
        "pip-audit",
    }.isdisjoint(requirements)


def _fake_ha_feature(mapping: dict[str, str]) -> Callable[[str], tuple[int, int]]:
    def resolve(phacc_version: str) -> tuple[int, int]:
        year, month = mapping[phacc_version].split(".")[:2]
        return (int(year), int(month))

    return resolve


def test_min_ha_version_candidates_picks_the_newest_eligible_patch_of_its_feature():
    # Real scenario this was built to fix: an earlier run picked whatever
    # phacc release resolved to homeassistant 2026.1.0 (the release
    # closest to the cutoff *at that time*), then later patches of the
    # very same 2026.1 line (.1, .2, .3) crossed the months-behind cutoff
    # too without ever being reconsidered. The first candidate must be the
    # newest *eligible* patch of the newest eligible feature line, not
    # whichever specific release happens to sit right at the cutoff.
    # phacc's own version numbers are an unrelated internal counter (real
    # example: "0.13.308") -- only the resolved HA version matters.
    releases = [
        ("0.13.100", "2026-01-06"),
        ("0.13.101", "2026-01-13"),
        ("0.13.102", "2026-01-20"),
        ("0.13.103", "2026-01-27"),
        ("0.13.104", "2026-02-03"),
    ]
    ha_feature = _fake_ha_feature(
        {
            "0.13.100": "2026.1.0",
            "0.13.101": "2026.1.1",
            "0.13.102": "2026.1.2",
            "0.13.103": "2026.1.3",
            "0.13.104": "2026.2.0",
        }
    )

    candidates = update_dependencies.min_ha_version_candidates(
        releases, cutoff="2026-01-31", max_attempts=12, ha_feature=ha_feature
    )

    assert candidates[0] == "0.13.103"


def test_min_ha_version_candidates_walks_forward_by_whole_feature_line():
    # Once the target line doesn't resolve (the caller drops a candidate
    # after a failed compile), the next attempt must be the *next feature
    # line's* newest patch -- never an earlier patch of the same line that
    # already failed (they share the same dependency floor) or the next
    # line's oldest patch when a newer one of it already exists too.
    releases = [
        ("0.13.100", "2026-01-06"),
        ("0.13.101", "2026-01-13"),
        ("0.13.102", "2026-02-03"),
        ("0.13.103", "2026-02-10"),
        ("0.13.104", "2026-03-03"),
    ]
    ha_feature = _fake_ha_feature(
        {
            "0.13.100": "2026.1.0",
            "0.13.101": "2026.1.1",
            "0.13.102": "2026.2.0",
            "0.13.103": "2026.2.1",
            "0.13.104": "2026.3.0",
        }
    )

    candidates = update_dependencies.min_ha_version_candidates(
        releases, cutoff="2026-01-31", max_attempts=12, ha_feature=ha_feature
    )

    assert candidates == ["0.13.101", "0.13.103", "0.13.104"]


def test_min_ha_version_candidates_only_bounds_the_first_feature_by_cutoff():
    # Walking forward past the months-behind target already means
    # exceeding it to find something that resolves -- every feature line
    # after the first uses its true latest patch regardless of whether
    # that specific patch's own release date crosses the cutoff.
    releases = [
        ("0.13.100", "2026-01-06"),
        ("0.13.101", "2026-06-01"),
        ("0.13.102", "2027-01-01"),  # released after "today" in this test
    ]
    ha_feature = _fake_ha_feature(
        {
            "0.13.100": "2026.1.0",
            "0.13.101": "2026.2.0",
            "0.13.102": "2026.2.1",
        }
    )

    candidates = update_dependencies.min_ha_version_candidates(
        releases, cutoff="2026-01-10", max_attempts=12, ha_feature=ha_feature
    )

    assert candidates == ["0.13.100", "0.13.102"]


def test_min_ha_version_candidates_respects_max_attempts_as_a_feature_budget():
    releases = [
        ("0.13.100", "2026-01-06"),
        ("0.13.101", "2026-02-03"),
        ("0.13.102", "2026-03-03"),
        ("0.13.103", "2026-04-03"),
    ]
    ha_feature = _fake_ha_feature(
        {
            "0.13.100": "2026.1.0",
            "0.13.101": "2026.2.0",
            "0.13.102": "2026.3.0",
            "0.13.103": "2026.4.0",
        }
    )

    candidates = update_dependencies.min_ha_version_candidates(
        releases, cutoff="2026-01-10", max_attempts=2, ha_feature=ha_feature
    )

    assert candidates == ["0.13.100", "0.13.101"]


def test_min_ha_version_candidates_raises_when_nothing_is_old_enough():
    releases = [("0.13.100", "2026-01-06")]

    def unused_ha_feature(_phacc_version: str) -> tuple[int, int]:
        raise AssertionError("must fail before ever resolving an HA feature")

    with pytest.raises(SystemExit, match="no pytest-homeassistant-custom-component"):
        update_dependencies.min_ha_version_candidates(
            releases, cutoff="2025-01-01", max_attempts=12, ha_feature=unused_ha_feature
        )
